export const missions = [
  {
    title: "싸피 토익",
    description: "토익 공부 최고",
    participantsCount: 99,
    mainCategory: "STUDY",
    subCategory: "LANGUAGE",
  },
  {
    title: "싸피 토익",
    description: "토익 공부 최고",
    participantsCount: 99,
    mainCategory: "STUDY",
    subCategory: "LANGUAGE",
  },
  {
    title: "싸피 토익",
    description: "토익 공부 최고",
    participantsCount: 99,
    mainCategory: "STUDY",
    subCategory: "LANGUAGE",
  },
  {
    title: "싸피 토익",
    description: "토익 공부 최고",
    participantsCount: 99,
    mainCategory: "STUDY",
    subCategory: "LANGUAGE",
  },
  {
    title: "싸피 토익",
    description: "토익 공부 최고",
    participantsCount: 99,
    mainCategory: "STUDY",
    subCategory: "LANGUAGE",
  },
  {
    title: "싸피 토익",
    description: "토익 공부 최고",
    participantsCount: 99,
    mainCategory: "STUDY",
    subCategory: "LANGUAGE",
  },
  {
    title: "싸피 토익",
    description: "토익 공부 최고",
    participantsCount: 99,
    mainCategory: "STUDY",
    subCategory: "LANGUAGE",
  },
  {
    title: "싸피 토익",
    description: "토익 공부 최고",
    participantsCount: 99,
    mainCategory: "STUDY",
    subCategory: "LANGUAGE",
  },
  {
    title: "싸피 토익",
    description: "토익 공부 최고",
    participantsCount: 99,
    mainCategory: "STUDY",
    subCategory: "LANGUAGE",
  },
  {
    title: "싸피 토익",
    description: "토익 공부 최고",
    participantsCount: 99,
    mainCategory: "STUDY",
    subCategory: "LANGUAGE",
  },
];
